# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d775ac2bf55c66ac7d6c3a569e60ecbcf5efccaa14f33e3afcea89fd6f6e650c73c2fb7971675937fc9191ae944b2b0faea6f259380d6ae324c70c066ce8bb7f

test:
  secret_key_base: fc3be97fae11a48abf393f5b42bb93d777a229a37b18bb30e09f8292ec11f79193c4ed7afeba590f94e9ae79d629be0a7538b4b2efa73b377cae7aacdb83b6d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
